version: "3"
services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile.server
    ports:
      - "8080:8080"
  client:
    build:
      context: ./
      dockerfile: Dockerfile.client
    ports:
      - "4000:80"
    links:
      - server
